FROM python:3.10-slim

WORKDIR /app

# テスト実行に必要なパッケージをインストール
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest

# アプリのコードもコピー
COPY . .

# デフォルトコマンドはpytest実行
CMD ["pytest", "tests/"]