# Generated by Django 4.2.24 on 2025-09-23 17:32

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models


def create_citext_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS citext")
import django.db.models.deletion
import django.utils.timezone
import quiz.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_citext_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('oauth_provider', models.CharField(default='google', max_length=32)),
                ('oauth_sub', models.CharField(max_length=255)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', quiz.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.UUIDField(db_column='invitation_code_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_code', models.CharField(max_length=24, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invitation_codes',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='quiz_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('timer_seconds', models.IntegerField(blank=True, default=10, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='quiz_collection_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('default', 'default'), ('custom', 'custom')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quiz_collections',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='quiz_question_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_order', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.UUIDField(db_column='quiz_result_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_ms', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'quiz_results',
            },
        ),
        migrations.CreateModel(
            name='QuizResultDetail',
            fields=[
                ('id', models.UUIDField(db_column='quiz_result_detail_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_order', models.IntegerField()),
                ('selected_text', models.CharField(blank=True, max_length=120, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('reaction_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_result_details',
            },
        ),
        migrations.CreateModel(
            name='RosterFolder',
            fields=[
                ('id', models.UUIDField(db_column='roster_folder_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_dynamic', models.BooleanField(default=False)),
                ('dynamic_filter', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roster_folders',
            },
        ),
        migrations.CreateModel(
            name='RosterMembership',
            fields=[
                ('id', models.UUIDField(db_column='roster_membership_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'roster_memberships',
            },
        ),
        migrations.CreateModel(
            name='StudentTeacherLink',
            fields=[
                ('id', models.UUIDField(db_column='student_teacher_link_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('revoked', 'revoked')], default='active', max_length=16)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('custom_display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('private_note', models.TextField(blank=True, null=True)),
                ('local_student_code', models.CharField(blank=True, max_length=64, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('kana_for_sort', models.CharField(blank=True, max_length=160, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_teacher_links',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='teacher_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('oauth_provider', models.CharField(default='google', max_length=32)),
                ('oauth_sub', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='test_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts_per_student', models.IntegerField(default=1000)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='quiz.teacher')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestAssignee',
            fields=[
                ('id', models.UUIDField(db_column='test_assignee_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(blank=True, max_length=16, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('assigned_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_assignees', to='quiz.teacher')),
                ('source_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_assignees', to='quiz.rosterfolder')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_assignments', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='quiz.test')),
            ],
            options={
                'db_table': 'test_assignees',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(db_column='test_result_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='results', to='quiz.test')),
                ('test_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='quiz.testassignee')),
            ],
            options={
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='quiz.teacher')),
                ('display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=120, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teachers_profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=120)),
                ('avatar_url', models.TextField()),
                ('grade', models.CharField(blank=True, max_length=32, null=True)),
                ('self_intro', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='vocabulary_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_en', models.CharField(max_length=120)),
                ('text_key', django.contrib.postgres.fields.citext.CITextField(editable=False)),
                ('part_of_speech', models.CharField(blank=True, max_length=30, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('example_en', models.TextField(blank=True, null=True)),
                ('example_ja', models.TextField(blank=True, null=True)),
                ('sort_key', models.CharField(editable=False, max_length=255)),
                ('head_letter', models.CharField(editable=False, max_length=1)),
                ('sense_count', models.IntegerField(default=1)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('proposed', 'proposed'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('alias_of', models.ForeignKey(blank=True, db_column='alias_of_vocabulary_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='quiz.vocabulary')),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vocabularies', to='quiz.teacher')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vocabularies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabularies',
            },
        ),
        migrations.CreateModel(
            name='VocabTranslation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='vocab_translation_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_ja', models.CharField(max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.vocabulary')),
            ],
            options={
                'db_table': 'vocab_translations',
            },
        ),
        migrations.CreateModel(
            name='VocabChoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='vocab_choice_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_ja', models.CharField(max_length=120)),
                ('is_correct', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('source_vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_choices', to='quiz.vocabulary')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.vocabulary')),
            ],
            options={
                'db_table': 'vocab_choice_bank',
            },
        ),
        migrations.CreateModel(
            name='TestResultDetail',
            fields=[
                ('id', models.UUIDField(db_column='test_result_detail_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_order', models.IntegerField()),
                ('selected_text', models.CharField(blank=True, max_length=120, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('reaction_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_result_details', to='quiz.vocabchoice')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quiz.testresult')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_result_details', to='quiz.vocabulary')),
            ],
            options={
                'db_table': 'test_result_details',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.UUIDField(db_column='test_question_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_order', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=4, null=True)),
                ('timer_seconds', models.IntegerField(default=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_questions', to='quiz.vocabulary')),
            ],
            options={
                'db_table': 'test_questions',
            },
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.UUIDField(db_column='test_assignment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('run_params', models.JSONField(blank=True, null=True)),
                ('assigned_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_assignments', to='quiz.teacher')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quiz.test')),
            ],
            options={
                'db_table': 'test_assignments',
            },
        ),
        migrations.AddField(
            model_name='testassignee',
            name='test_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignees', to='quiz.testassignment'),
        ),
        migrations.CreateModel(
            name='TeacherWhitelist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='teachers_whitelist_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('can_publish_vocab', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whitelists', to='quiz.teacher')),
            ],
            options={
                'db_table': 'teachers_whitelists',
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='teachers_email_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['oauth_provider'], name='teachers_oauth_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['disabled_at'], name='teachers_disabled_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['deleted_at'], name='teachers_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_login'], name='teachers_lastlogin_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('deleted_at__isnull', True)), name='teachers_email_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('oauth_provider', 'oauth_sub'), name='teachers_oauth_uniq'),
        ),
        migrations.AddField(
            model_name='studentteacherlink',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_teacher_links', to='quiz.invitationcode'),
        ),
        migrations.AddField(
            model_name='studentteacherlink',
            name='revoked_by_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_teacher_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentteacherlink',
            name='revoked_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_links', to='quiz.teacher'),
        ),
        migrations.AddField(
            model_name='studentteacherlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentteacherlink',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='quiz.teacher'),
        ),
        migrations.AddField(
            model_name='rostermembership',
            name='roster_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='quiz.rosterfolder'),
        ),
        migrations.AddField(
            model_name='rostermembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosterfolder',
            name='owner_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_folders', to='quiz.teacher'),
        ),
        migrations.AddField(
            model_name='rosterfolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.rosterfolder'),
        ),
        migrations.AddField(
            model_name='quizresultdetail',
            name='quiz_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quiz.quizresult'),
        ),
        migrations.AddField(
            model_name='quizresultdetail',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quiz_result_details', to='quiz.vocabulary'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='results', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quiz_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quiz_questions', to='quiz.vocabulary'),
        ),
        migrations.AddField(
            model_name='quizcollection',
            name='origin_collection',
            field=models.ForeignKey(blank=True, db_column='origin_collection_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_collections', to='quiz.quizcollection'),
        ),
        migrations.AddField(
            model_name='quizcollection',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='origin_quiz',
            field=models.ForeignKey(blank=True, db_column='origin_quiz_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_quizzes', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.quizcollection'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_invitation_codes', to='quiz.teacher'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['sort_key'], name='vocab_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['head_letter'], name='vocab_head_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['visibility'], name='vocab_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['status'], name='vocab_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['archived_at'], name='vocab_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.CheckConstraint(check=models.Q(('visibility', 'public'), ('created_by_user__isnull', False), ('created_by_teacher__isnull', False), _connector='OR'), name='vocab_owner_required'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.CheckConstraint(check=models.Q(('created_by_user__isnull', False), ('created_by_teacher__isnull', False), _negated=True), name='vocab_single_owner'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published'), ('visibility', 'public')), fields=('text_key',), name='vocab_public_unique'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by_user__isnull', False), ('visibility', 'private')), fields=('text_key', 'created_by_user'), name='vocab_private_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by_teacher__isnull', False), ('visibility', 'private')), fields=('text_key', 'created_by_teacher'), name='vocab_private_teacher_unique'),
        ),
        migrations.AddIndex(
            model_name='vocabtranslation',
            index=models.Index(fields=['vocabulary'], name='vtrans_vocab_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabtranslation',
            index=models.Index(fields=['is_primary'], name='vtrans_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabtranslation',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'text_ja'), name='vocab_trans_unique'),
        ),
        migrations.AddConstraint(
            model_name='vocabtranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('vocabulary',), name='vocab_trans_primary_unique'),
        ),
        migrations.AddIndex(
            model_name='vocabchoice',
            index=models.Index(fields=['vocabulary'], name='vchoice_vocab_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabchoice',
            index=models.Index(fields=['vocabulary', 'is_correct'], name='vchoice_correct_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabchoice',
            index=models.Index(fields=['vocabulary', 'weight'], name='vchoice_weight_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabchoice',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'text_ja'), name='vocab_choice_unique'),
        ),
        migrations.AddIndex(
            model_name='testresultdetail',
            index=models.Index(fields=['test_result'], name='trd_result_idx'),
        ),
        migrations.AddIndex(
            model_name='testresultdetail',
            index=models.Index(fields=['vocabulary'], name='trd_vocab_idx'),
        ),
        migrations.AddIndex(
            model_name='testresultdetail',
            index=models.Index(fields=['created_at'], name='trd_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='testresultdetail',
            constraint=models.UniqueConstraint(fields=('test_result', 'question_order'), name='test_result_detail_order_unique'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['test'], name='tr_test_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['student', 'started_at'], name='tr_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('test', 'student', 'attempt_no'), name='test_result_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(condition=models.Q(('test_assignee__isnull', False)), fields=('test_assignee', 'attempt_no'), name='test_result_assignee_unique'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.CheckConstraint(check=models.Q(('attempt_no__gte', 1)), name='test_result_attempt_check'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['test'], name='tq_test_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['vocabulary'], name='tq_vocab_idx'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'question_order'), name='test_question_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.CheckConstraint(check=models.Q(('timer_seconds__gt', 0)), name='test_question_timer_check'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['test'], name='ta_test_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['assigned_at'], name='ta_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignee',
            index=models.Index(fields=['test'], name='tas_test_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignee',
            index=models.Index(fields=['student'], name='tas_student_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignee',
            index=models.Index(fields=['assigned_at'], name='tas_assigned_idx'),
        ),
        migrations.AddConstraint(
            model_name='testassignee',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='test_assignee_unique'),
        ),
        migrations.AddConstraint(
            model_name='testassignee',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts__isnull', True), ('max_attempts__gte', 1), _connector='OR'), name='test_assignee_max_check'),
        ),
        migrations.AddConstraint(
            model_name='testassignee',
            constraint=models.CheckConstraint(check=models.Q(('source_type__isnull', True), ('source_type__in', ['folder', 'manual', 'api']), _connector='OR'), name='test_assignee_source_check'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['teacher'], name='tests_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['due_at'], name='tests_due_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['archived_at'], name='tests_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts_per_student__gte', 1)), name='tests_max_attempts_check'),
        ),
        migrations.AddIndex(
            model_name='teacherwhitelist',
            index=models.Index(fields=['email'], name='tw_email_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherwhitelist',
            index=models.Index(fields=['can_publish_vocab'], name='tw_publish_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherwhitelist',
            index=models.Index(fields=['revoked_at'], name='tw_revoked_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherwhitelist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('revoked_at__isnull', True)), name='tw_email_active_uniq'),
        ),
        migrations.AddIndex(
            model_name='studentteacherlink',
            index=models.Index(fields=['teacher', 'status'], name='st_links_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='studentteacherlink',
            index=models.Index(fields=['student', 'status'], name='st_links_student_idx'),
        ),
        migrations.AddIndex(
            model_name='studentteacherlink',
            index=models.Index(fields=['linked_at'], name='st_links_linked_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentteacherlink',
            constraint=models.UniqueConstraint(fields=('teacher', 'student'), name='st_links_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='studentteacherlink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by_teacher__isnull', True), ('revoked_by_student__isnull', True)), models.Q(('revoked_at__isnull', False), models.Q(models.Q(('revoked_by_teacher__isnull', False), ('revoked_by_student__isnull', True)), models.Q(('revoked_by_teacher__isnull', True), ('revoked_by_student__isnull', False)), _connector='OR')), _connector='OR'), name='st_links_revoked_check'),
        ),
        migrations.AddIndex(
            model_name='rostermembership',
            index=models.Index(fields=['roster_folder'], name='rm_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='rostermembership',
            index=models.Index(fields=['student'], name='rm_student_idx'),
        ),
        migrations.AddIndex(
            model_name='rostermembership',
            index=models.Index(fields=['removed_at'], name='rm_removed_idx'),
        ),
        migrations.AddConstraint(
            model_name='rostermembership',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('roster_folder', 'student'), name='rm_active_unique'),
        ),
        migrations.AddIndex(
            model_name='rosterfolder',
            index=models.Index(fields=['owner_teacher'], name='rf_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterfolder',
            index=models.Index(fields=['parent_folder'], name='rf_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterfolder',
            index=models.Index(fields=['archived_at'], name='rf_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterfolder',
            index=models.Index(fields=['created_at'], name='rf_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='rosterfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_folder__isnull', False)), fields=('owner_teacher', 'parent_folder', 'name'), name='rf_unique_child'),
        ),
        migrations.AddConstraint(
            model_name='rosterfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_folder__isnull', True)), fields=('owner_teacher', 'name'), name='rf_unique_root'),
        ),
        migrations.AddConstraint(
            model_name='rosterfolder',
            constraint=models.CheckConstraint(check=models.Q(('parent_folder', models.F('id')), _negated=True), name='rf_no_self_parent'),
        ),
        migrations.AddIndex(
            model_name='quizresultdetail',
            index=models.Index(fields=['quiz_result'], name='qrd_result_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresultdetail',
            index=models.Index(fields=['vocabulary'], name='qrd_vocab_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresultdetail',
            index=models.Index(fields=['created_at'], name='qrd_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizresultdetail',
            constraint=models.UniqueConstraint(fields=('quiz_result', 'question_order'), name='quiz_result_detail_order_unique'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['user', 'started_at'], name='qr_user_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['quiz'], name='qr_quiz_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz'], name='qq_quiz_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['vocabulary'], name='qq_vocab_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['archived_at'], name='qq_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('quiz', 'question_order'), name='quiz_question_order_unique'),
        ),
        migrations.AddIndex(
            model_name='quizcollection',
            index=models.Index(fields=['scope', 'owner_user'], name='qc_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='quizcollection',
            index=models.Index(fields=['archived_at'], name='qc_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizcollection',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('owner_user', 'title'), name='quiz_collection_title_unique'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_collection'], name='quiz_collection_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['archived_at'], name='quiz_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('quiz_collection', 'sequence_no'), name='quiz_sequence_unique'),
        ),
        migrations.AddIndex(
            model_name='invitationcode',
            index=models.Index(fields=['invitation_code'], name='inv_codes_code_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationcode',
            index=models.Index(fields=['issued_at'], name='inv_codes_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationcode',
            index=models.Index(fields=['expires_at'], name='inv_codes_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationcode',
            index=models.Index(fields=['used_at'], name='inv_codes_used_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['oauth_provider'], name='users_oauth_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['disabled_at'], name='users_disabled_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='users_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='users_lastlogin_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('deleted_at__isnull', True)), name='users_email_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('oauth_provider', 'oauth_sub'), name='users_oauth_uniq'),
        ),
    ]
