# Generated by Django 4.2.24 on 2025-09-11 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('reaction_time_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('default', '順番通り'), ('random', 'ランダム')], default='default', max_length=10)),
                ('level', models.IntegerField(choices=[(1, 'レベル1'), (2, 'レベル2'), (3, 'レベル3'), (4, 'レベル4')])),
                ('segment', models.IntegerField(choices=[(1, 'セグメント1'), (2, 'セグメント2'), (3, 'セグメント3')])),
                ('question_count', models.IntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'レベル1'), (2, 'レベル2'), (3, 'レベル3'), (4, 'レベル4')])),
                ('segment', models.IntegerField(choices=[(1, 'セグメント1'), (2, 'セグメント2'), (3, 'セグメント3')])),
                ('difficulty', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level_preference',
            field=models.IntegerField(choices=[(1, 'レベル1'), (2, 'レベル2'), (3, 'レベル3'), (4, 'レベル4')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '生徒'), ('teacher', '教師'), ('admin', '管理者')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.word')),
            ],
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['level', 'segment'], name='quiz_word_level_07fdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['difficulty'], name='quiz_word_difficu_0a157c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('text', 'level', 'segment')},
        ),
        migrations.AddField(
            model_name='quizset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='quiz_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizitem'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='quiz_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='quiz.quizset'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='selected_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.wordtranslation'),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='quiz_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_items', to='quiz.quizset'),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.word'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['word', 'is_correct'], name='quiz_wordtr_word_id_3968a8_idx'),
        ),
        migrations.AddIndex(
            model_name='quizset',
            index=models.Index(fields=['user', 'created_at'], name='quiz_quizse_user_id_65e933_idx'),
        ),
        migrations.AddIndex(
            model_name='quizset',
            index=models.Index(fields=['level', 'segment'], name='quiz_quizse_level_27620d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponse',
            index=models.Index(fields=['quiz_set'], name='quiz_quizre_quiz_se_140513_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponse',
            index=models.Index(fields=['created_at'], name='quiz_quizre_created_58e09e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together={('quiz_set', 'quiz_item')},
        ),
        migrations.AddIndex(
            model_name='quizitem',
            index=models.Index(fields=['quiz_set', 'order'], name='quiz_quizit_quiz_se_665182_idx'),
        ),
    ]
