# Generated by Django 4.2.24 on 2025-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_align_with_design'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='users_email_active_uniq',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='text_key',
            field=models.TextField(db_collation='case_insensitive', editable=False),
        ),
    ]
