# Generated by Django 4.2.24 on 2025-09-13 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStudentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('active', '有効'), ('revoked', '解除済み')], default='active', max_length=10)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.invitecode')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['teacher', 'status'], name='quiz_teache_teacher_482acf_idx'), models.Index(fields=['student', 'status'], name='quiz_teache_student_46607f_idx'), models.Index(fields=['linked_at'], name='quiz_teache_linked__0fa153_idx')],
                'unique_together': {('teacher', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['code'], name='quiz_invite_code_2a9f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['issued_by', 'issued_at'], name='quiz_invite_issued__4d2046_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['expires_at'], name='quiz_invite_expires_1a2260_idx'),
        ),
    ]
