# Generated by Django 4.2.24 on 2025-09-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_teacherwhitelist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacherwhitelist',
            table='quiz_whitelist_user',
        ),
    ]
