# Generated by hand for adding TeacherStudentAlias and Group unique/indexes
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_revert_teacherwhitelist_minimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentAlias',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('alias_name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_aliases', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_aliases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='teacherstudentalias',
            constraint=models.UniqueConstraint(fields=('teacher', 'student'), name='quiz_teacherstudentalias_unique_teacher_student'),
        ),
        migrations.AddIndex(
            model_name='teacherstudentalias',
            index=models.Index(fields=['teacher'], name='quiz_tsalias_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherstudentalias',
            index=models.Index(fields=['student'], name='quiz_tsalias_student_idx'),
        ),
                # Conditionally apply unique/indexes if quiz_group exists (to be safe for existing DBs)
                migrations.RunSQL(
                        sql=(
                                """
                                DO $$
                                BEGIN
                                    IF EXISTS (
                                        SELECT 1 FROM information_schema.tables WHERE table_name='quiz_group'
                                    ) THEN
                                        -- Unique constraint on (owner_admin_id, name)
                                        IF NOT EXISTS (
                                            SELECT 1 FROM pg_constraint WHERE conname = 'quiz_group_owner_admin_id_name_uniq'
                                        ) THEN
                                            ALTER TABLE "quiz_group" ADD CONSTRAINT "quiz_group_owner_admin_id_name_uniq" UNIQUE ("owner_admin_id", "name");
                                        END IF;
                                        -- Indexes
                                        CREATE INDEX IF NOT EXISTS quiz_group_owner_idx ON "quiz_group" ("owner_admin_id");
                                        CREATE INDEX IF NOT EXISTS quiz_group_name_idx ON "quiz_group" ("name");
                                    END IF;
                                END
                                $$;
                                """
                        ),
                        reverse_sql=(
                                """
                                DO $$
                                BEGIN
                                    IF EXISTS (
                                        SELECT 1 FROM information_schema.tables WHERE table_name='quiz_group'
                                    ) THEN
                                        IF EXISTS (
                                            SELECT 1 FROM pg_constraint WHERE conname = 'quiz_group_owner_admin_id_name_uniq'
                                        ) THEN
                                            ALTER TABLE "quiz_group" DROP CONSTRAINT "quiz_group_owner_admin_id_name_uniq";
                                        END IF;
                                        DROP INDEX IF EXISTS quiz_group_owner_idx;
                                        DROP INDEX IF EXISTS quiz_group_name_idx;
                                    END IF;
                                END
                                $$;
                                """
                        )
                ),
    ]
