# Generated by Django 4.2.24 on 2025-09-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_perf_indexes'),
        ('quiz', '0011_groups_and_alias'),
    ]

    operations = [
    ]
