# Generated by Django 4.2.24 on 2025-09-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_insert_sample_data'),
        ('quiz', '0018_test_templates_and_assignedtest_ext'),
    ]

    operations = [
    ]
